.PHONY:

build:
    docker-compose up --build

up:
    docker-compose up

up-detached:
    docker-compose up -d

stop:
    docker-compose stop

down:
    docker-compose down

logs:
    docker-compose logs -f